### PR TITLE
Disallow duplicate indexes and updated UG

### LINKED ISSUE #249: [PE-D] "delete 1 1" deletes the top 2 results
^before

^after

This may be a potential bug when the user accidentally types the same number multiple times but only wants to delete one person.

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: ChuangZheQuan/ped#1

### LINKED ISSUE #263: [PE-D] delete 1 1 command has unexpected behaviour
`delete 1 1` deletes applicants at index 1 and 2. Expected to only delete applicant at index 1.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: wz27/ped#4

### LINKED ISSUE #265: [PE-D] delete 6 6 command has unexpected behaviour
`delete 6 6` returns error "The person index provided is invalid", but the applicant at index 6 is actually deleted in the GUI list. In addition, upon immediately exiting the application and opening the application, applicant at index 6 remains and is not deleted.

Expected success message, and applicant at index 6 is actually deleted.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: wz27/ped#5

### LINKED ISSUE #266: [PE-D] Typing "delete [last index] [last index]" will delete the last person while throwing an error
-------------
Labels: `severity.High` `type.FeatureFlaw`
original: ChuangZheQuan/ped#7

### LINKED ISSUE #267: [PE-D] Allows you to mark the person as done twice in one command
Don't really know if this is intended, but it is kind of weird to be able to mark done twice for a person in a single command. Maybe check for uniqueness?

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: ChuangZheQuan/ped#8

### LINKED ISSUE #280: [PE-D] 'delete' command deletes 2 different contacts even if the 2 index numbers passed in are the same
For instance, when the delete command `delete 1 1` is keyed in, the first 2 contacts are deleted although the user might have accidentally typed in the additional 1 and never meant for the 2nd contact to be deleted. So perhaps you could ignore the next index number if it is the same as the earlier index number?

Below are the before and after screenshots:

Both `Irfan` and `Roy` were deleted though `Irfan` was the only contact meant to be deleted.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Preshita01/ped#6

### PR DESCRIPTION
**Pull request by BryannYeap**
Removed the ability to delete and mark / unmark duplicate indexes. For instance, `delete 1 1` is no longer allowed.

### Issues fixed:
fixes #249 
fixes #263 
fixes #265 
fixes #266 
fixes #267 
fixes #280

Additionally, issue #257 brought to my attention some outdated lines in the UG, so I fixed it up.

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/DeleteCommand.java [hunk 1]
```diff
@@ -20,7 +20,7 @@
 
     public static final String MESSAGE_USAGE = COMMAND_WORD
             + ": Deletes the applicants identified by the index numbers used in the displayed person list.\n"
-            + "Parameters: INDEX... (must be positive integers)\n"
+            + "Parameters: INDEX...\n"
```
Comment (TohWeiJie01) [inline src/main/java/seedu/address/logic/commands/DeleteCommand.java:23]: Why not keep the (must be positive integers) in?

File: src/test/java/seedu/address/logic/parser/MarkingCommandParserTest.java [hunk 2]
```diff
@@ -42,34 +44,51 @@ public void parse_validArgs_returnsMarkingCommand() {
...
         assertParseFailure(parserForUnmark, "0 -1",
-                String.format(MESSAGE_INVALID_COMMAND_FORMAT, UnmarkCommand.MESSAGE_USAGE));
+                String.format(errorDueToInvalidIndex, UnmarkCommand.MESSAGE_USAGE));
+
+        // Multiple inputs, all valid, duplicates
+        assertParseFailure(parserForMark, "1 1",
+                String.format(errorDueToDuplicateIndex, MarkCommand.MESSAGE_USAGE)); // Only 2 inputs, duplicates
+        assertParseFailure(parserForUnmark, "1 1",
+                String.format(errorDueToDuplicateIndex, UnmarkCommand.MESSAGE_USAGE)); // Only 2 inputs, duplicates
+        assertParseFailure(parserForMark, "70 2 3 2 2 1 70",
```
Comment (TohWeiJie01) [inline src/test/java/seedu/address/logic/parser/MarkingCommandParserTest.java:85]: I think you can add a comment to tell that the duplicate index error will be thrown before the invalid range error

File: src/main/java/seedu/address/logic/commands/DeleteCommand.java (hunk 1 above)
Comment (BryannYeap) [reply src/main/java/seedu/address/logic/commands/DeleteCommand.java:23]: Ah because this message would only come up if they didn't input a positive integer, but I appended the error message from ParserUtil that would tell the user if they did not input a positive integer. So if I leave this in, it would tell the user twice. So might as well take out 😅
