### PR TITLE
Fix mark and unmark PED bug

### LINKED ISSUE #272: [PE-D] Unmarking a not done applicant does not return error
`unmark 1` returns success message. Expected to return error message since applicant at index 1 is not marked done.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: wz27/ped#7

### LINKED ISSUE #273: [PE-D] Should check if the application status is done or not done before marking or unmarking
Right now you still can unmark applicants who are not done. Not sure whether this is intended

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: ChuangZheQuan/ped#10

### LINKED ISSUE #274: [PE-D] Marking a done applicant does not return error
`mark 1` then `mark 1` does not return error. Expected to return error message since applicant at index 1 is already marked done.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: wz27/ped#8

### PR DESCRIPTION
**Pull request by TohWeiJie01**
### Changes
Fixes #272 
Fixes #273 
Fixes #274 
1) Disallow a "Done" applicant to be marked again.
2) Disallow a "Not Done" applicant to be unmarked again.

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/UnmarkCommand.java [hunk 1]
```diff
@@ -38,10 +40,19 @@ public CommandResult execute(Model model) throws CommandException {
...
 
-        for (Index targetIndex : targetIndexes) {
-            if (targetIndex.getZeroBased() >= lastShownList.size()) {
+        boolean unmarkingUnmarkedPerson;
+        for (Index checkIndex : targetIndexes) {
+            if (checkIndex.getZeroBased() >= lastShownList.size()) {
                 throw new CommandException(Messages.MESSAGE_INVALID_PERSON_DISPLAYED_INDEX);
             }
+            Person personToCheck = lastShownList.get(checkIndex.getZeroBased());
+            unmarkingUnmarkedPerson = model.checkForMarkedPerson(personToCheck);
```
Comment (BryannYeap) [inline src/main/java/seedu/address/logic/commands/UnmarkCommand.java:49]: I believe the line should be `unmarkingUnmarkedPerson = model.checkForUnmarkedPerson(personToCheck);`? 🐒

**Review by BryannYeap — COMMENTED** [review]
Almost LGTM!
