### PR TITLE
Fix unintended mark / unmark command behaviou

### LINKED ISSUE #304: Fix unintended mark / unmark command behaviour
Inputting `mark 1 2 70`, where 70 is an out of range index would result in RecruitIn marking 1 and 2 first, followed by throwing an error message for 70.

The intended behavior should be as follows: Any out of range index will automatically be detected and an error message will be thrown immediately. This behavior is consistent with `delete` command as well.

### PR DESCRIPTION
**Pull request by BryannYeap**
Fixes #304

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 1]
```diff
@@ -59,6 +60,8 @@ public static Index parseIndex(String oneBasedIndex) throws ParseException {
             }
             indexesList[i] = Index.fromOneBased(Integer.parseInt(trimmedIndex));
         }
+        // Sort the array from large to small so that invalid (out of range) index will be encountered first
```
Comment (TohWeiJie01) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java:63]: Maybe do you want to add into the Javadocs the behaviour of the parseMultipleIndex now?

**Review by TohWeiJie01 — COMMENTED** [review]
LGTM! Just perhaps one additional change?
